"""Stdlib-only Python host for the TeML interactive NDJSON protocol."""

from __future__ import annotations

from teml_host.engine import EngineInfo, engine_invocation, is_javascript_entry, resolve_engine
from teml_host.paint import paint
from teml_host.screen import PreferredFrame, ScreenBuffer, ScrollRegion, Viewport
from teml_host.session import Session, SessionError
from teml_host.terminal import MouseGuard, TermGuard, decode_sgr_mouse, map_scroll, require_posix_tty
from teml_host.types import (
    AppendCommand,
    ChangeEvent,
    CharCommand,
    ClickEvent,
    Command,
    ConfigureCommand,
    DocFormat,
    ErrorEvent,
    ExitCommand,
    ExitEvent,
    FrameFormat,
    FrameMode,
    FramePatch,
    FullFrame,
    KeyCommand,
    KeyModifiers,
    KeyName,
    PatchFrame,
    PointerCommand,
    ProtocolVersion,
    RemoveCommand,
    RenderCommand,
    ReplaceCommand,
    ResizeCommand,
    ScrollCommand,
    ScrollRegionMeta,
    SessionEvent,
    ToggleEvent,
    UnknownEvent,
    UpdateCommand,
    ViewportMeta,
    command_to_json,
    parse_event,
)

from teml_host.protocol import (
    CAPABILITY_DOCS,
    ENGINE_CAPABILITIES,
    MAX_CHAR_BYTES,
    MAX_DOCUMENT_BLOCKS,
    MAX_MUTATION_TARGET_CHILDREN,
    MAX_NDJSON_LINE_BYTES,
    MAX_RENDER_MARKUP_BYTES,
    MAX_SCROLL_ROWS,
    PROTOCOL_MAJOR,
    PROTOCOL_MINOR,
    PROTOCOL_VERSION,
)

__all__ = [
    "AppendCommand",
    "MAX_NDJSON_LINE_BYTES",
    "MouseGuard",
    "ChangeEvent",
    "CharCommand",
    "ClickEvent",
    "Command",
    "ConfigureCommand",
    "DocFormat",
    "EngineInfo",
    "ErrorEvent",
    "ExitCommand",
    "ExitEvent",
    "FrameFormat",
    "FrameMode",
    "FramePatch",
    "FullFrame",
    "KeyCommand",
    "KeyModifiers",
    "KeyName",
    "PatchFrame",
    "PointerCommand",
    "PreferredFrame",
    "ProtocolVersion",
    "RemoveCommand",
    "RenderCommand",
    "ReplaceCommand",
    "ResizeCommand",
    "ScreenBuffer",
    "ScrollCommand",
    "ScrollRegion",
    "ScrollRegionMeta",
    "Session",
    "SessionError",
    "SessionEvent",
    "TermGuard",
    "ToggleEvent",
    "UnknownEvent",
    "UpdateCommand",
    "Viewport",
    "ViewportMeta",
    "CAPABILITY_DOCS",
    "ENGINE_CAPABILITIES",
    "MAX_CHAR_BYTES",
    "MAX_DOCUMENT_BLOCKS",
    "MAX_MUTATION_TARGET_CHILDREN",
    "MAX_NDJSON_LINE_BYTES",
    "MAX_RENDER_MARKUP_BYTES",
    "MAX_SCROLL_ROWS",
    "PROTOCOL_MAJOR",
    "PROTOCOL_MINOR",
    "PROTOCOL_VERSION",
    "command_to_json",
    "decode_sgr_mouse",
    "engine_invocation",
    "is_javascript_entry",
    "map_scroll",
    "paint",
    "parse_event",
    "require_posix_tty",
    "resolve_engine",
]

__version__ = "0.1.0"
